name: Attach Label + Swift Lint

on: 
  pull_request:
    branches:    
      - '!release/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2
      
      - name: get App-version
        run: |
          TUIST_PATH="./Tuist/ProjectDescriptionHelpers/MainSetting.swift"
          step1=`sed -n '/let APP_VERSION/p' ${TUIST_PATH}`
          step2=`echo ${step1} | sed 's/let APP_VERSION = //g'`
          step3=`echo ${step2} | sed 's/"//g'`
          echo "APP_VERSION=${step3}" >> $GITHUB_ENV
        
      - name: check branch + tags
        run: |
          BRANCH_TREE=${{ github.head_ref }}
          DETECT_VERTICAL=("parking" "rentcar")
          DETECT_TAGS=("bug" "improve" "feature")
          SELECTED_TAGS=(${{ env.APP_VERSION }})

          function detect_tag() {
              for tag in ${DETECT_TAGS[@]}
              do
                  if echo ${BRANCH_TREE} | grep -iqF ${tag} ; then
                      SELECTED_TAGS+=(${tag})
                  fi
              done
          }

          function detect_vertical() {
              for vertical in ${DETECT_VERTICAL[@]}
              do
                  if echo ${BRANCH_TREE} | grep -iqF ${vertical} ; then
                      SELECTED_TAGS+=(${vertical})
                  fi
              done
          }

          function detect_rt() {
              TREE_SPLIT=($(echo $BRANCH_TREE | tr "/" "\n"))
              for word in "${TREE_SPLIT[@]}"
              do
                  for ((i = 1; i <= 40; i++)); do
                      up_word=`echo $word | tr '[:lower:]' '[:upper:]'`
                      if [ "${up_word}" == "RT${i}" ]; then
                          SELECTED_TAGS+=( `echo ${up_word} | tr [a-z] [A-Z]` )
                      fi
                  done
              done
          }

          function sum_tags() {
              i=0
              TAGS_TEXT=""
              for word in "${SELECTED_TAGS[@]}"
              do
                  let i=i+1
                  if [ $i -eq 1 ]; then
                      TAGS_TEXT="${word}"
                  else
                      TAGS_TEXT="${TAGS_TEXT},${word}"
                  fi
              done
          }

          detect_tag
          detect_vertical
          detect_rt
          sum_tags

          echo "TAGS_TEXT=${TAGS_TEXT}" >> $GITHUB_ENV
        
      - name: Add labels
        uses: KeisukeYamashita/attach-labels@v1
        with:
          labels: ${{ env.TAGS_TEXT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                
      - name: Lint code using SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1




      
