name: Attach Label

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2
      
      - name: get App-version
        run: |
          TUIST_PATH="./Tuist/ProjectDescriptionHelpers/MainSetting.swift"
          step1=`sed -n '/let APP_VERSION/p' ${TUIST_PATH}`
          step2=`echo ${step1} | sed 's/let APP_VERSION = //g'`
          step3=`echo ${step2} | sed 's/"//g'`
          echo "APP_VERSION=${step3}" >> $GITHUB_ENV
        
      - name: check branch + tags
        run: |
          BRANCH_TREE=${{ github.head_ref }}
          CURRNET_TAG=${{ github.tag_name }}
          DETECT_TAGS=("bug" "improve" "feature")
          SELECTED_TAGS=(${{ env.APP_VERSION }})

          function detect_tag() {
              if echo ${BRANCH_TREE} | grep -iqF $1 ; then
                  SELECTED_TAGS+=($1)
              fi
          }

          function detect_rt() {
              TREE_SPLIT=($(echo $BRANCH_TREE | tr "/" "\n"))
              for (( i=0; i<${#TREE_SPLIT[@]}; i++ )); do
                  if echo ${TREE_SPLIT[i]} | grep -iqF RT ; then
                      SELECTED_TAGS+=( `echo ${TREE_SPLIT[i]} | tr [a-z] [A-Z]` )
                  fi
              done
          }

          for tag in ${DETECT_TAGS[@]}
          do
              detect_tag ${tag}
          done
          detect_rt

          i=0
          TAGS_TEXT=""
          for word in "${SELECTED_TAGS[@]}"
          do
              let i=i+1
              if [ $i -eq 1 ]; then
                  TAGS_TEXT="${word}"
              else
                  TAGS_TEXT="${TAGS_TEXT},${word}"
              fi
          done

          echo ${{ env.APP_VERSION }}
          echo ${TAGS_TEXT}
          echo ${CURRNET_TAG}
          echo "TAGS_TEXT=${TAGS_TEXT}" >> $GITHUB_ENV
        
      - name: Add labels
        uses: KeisukeYamashita/attach-labels@v1
        with:
          labels: ${{ env.TAGS_TEXT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
#       - name: Lint code using SwiftLint
#         uses: norio-nomura/action-swiftlint@3.2.1
      
