name: Build Actions

on: [pull_request_target]
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2
        
      - name: check branch + tags
        run: |
          BRANCH_TREE=${{ github.head_ref }}
          echo ${BRANCH_TREE}
          SELECTED_TAGS=()
          
          if echo ${BRANCH_TREE} | grep -iqF bug ; then
            SELECTED_TAGS+=("bug,")
          fi

          if echo ${BRANCH_TREE} | grep -iqF improve ; then
              SELECTED_TAGS+=("improve,")
          fi

          if echo ${BRANCH_TREE} | grep -iqF feature ; then
              SELECTED_TAGS+=("feature,")
          fi

          TREE_SPLIT=($(echo $BRANCH_TREE | tr "/" "\n"))
          for (( i=0; i<${#TREE_SPLIT[@]}; i++ )); do
              if echo ${TREE_SPLIT[i]} | grep -iqF RT ; then
                  SELECTED_TAGS+=( `echo "${TREE_SPLIT[i]}," | tr [a-z] [A-Z]` )
              fi
          done
          
          i=0
          TAGS_TEXT=""
          for word in "${SELECTED_TAGS[@]}"
          do
              let i=i+1
              if [ $i -eq 1 ]; then
                  TAGS_TEXT="${word}"
              else
                  TAGS_TEXT="${TAGS_TEXT},${word}"
              fi
          done

          echo ${TAGS_TEXT}
          echo "TAGS_TEXT=${TAGS_TEXT}" >> $GITHUB_ENV
        
      - name: Add labels
        uses: KeisukeYamashita/attach-labels@v1
        with:
          labels: ${{ env.TAGS_TEXT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

                    
        
#       - name : Print Title of PR
#         run: echo The Title of your PR is ${{ github.event.pull_request.title }}, {{ ./Todo/Info.plist }}
    
#       - uses: actions/checkout@v2
          
#       - name: Lint code using SwiftLint
#         uses: norio-nomura/action-swiftlint@3.2.1
                  
#       - name: Label from Info.plist
#         uses: classpass/label-ios-version-info-plist-action@v1.0.0
#         with:
#           repo-token: "${{ secrets.GITHUB_TOKEN }}"
#           info-plist-path: './Todo/Info.plist'
#           label-format: 'iOS {version}' # optional

#       - name: Echo PR Branch
#         run: |
#           echo "CURRENT_BRANCH=$( ${{github.head_ref}} | tr '/' '\n')" >> $GITHUB_ENV
      
#       - name: ECHO BRANCH
#         run: |
#           echo ${{ env.CURRENT_BRANCH }}
#          current_branch: ${{ github.head_ref }}
#          tree: ${{ current_branch }}.split('/')
#          echo "${{ tree }}"
#          echo "${{ tree[0] }}"
#          echo "${{ github.event.pull_request.head.ref }}" parking/feature/TEST
#          echo "github.base_ref: ${{ github.base_ref }}" main
#          echo "github.head_ref: ${{ github.head_ref }}" parking/feature/TEST
#          echo "github.ref: ${{ github.ref }}" ref/heads/main
