name: Build Actions

#on: [pull_request_target]
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Run a multi-line script
        run: |
          echo Run a multi-line script
          ls -a
          echo "${{ github.head_ref }}"
        
      - name: Run tests
        run: CI=1 sh ./scripts/branch+label.sh "Unix"
        
        
#       - name : Print Title of PR
#         run: echo The Title of your PR is ${{ github.event.pull_request.title }}, {{ ./Todo/Info.plist }}
    
#       - uses: actions/checkout@v2
#       - uses: christianvuerings/add-labels@v1
#         with:
#           labels: |
#             ${{ github.event.pull_request.title }}
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
#       - name: Lint code using SwiftLint
#         uses: norio-nomura/action-swiftlint@3.2.1
                  
#       - name: Label from Info.plist
#         uses: classpass/label-ios-version-info-plist-action@v1.0.0
#         with:
#           repo-token: "${{ secrets.GITHUB_TOKEN }}"
#           info-plist-path: './Todo/Info.plist'
#           label-format: 'iOS {version}' # optional

#       - name: Echo PR Branch
#         run: |
#           echo "CURRENT_BRANCH=$( ${{github.head_ref}} | tr '/' '\n')" >> $GITHUB_ENV
      
#       - name: ECHO BRANCH
#         run: |
#           echo ${{ env.CURRENT_BRANCH }}
#          current_branch: ${{ github.head_ref }}
#          tree: ${{ current_branch }}.split('/')
#          echo "${{ tree }}"
#          echo "${{ tree[0] }}"
#          echo "${{ github.event.pull_request.head.ref }}" parking/feature/TEST
#          echo "github.base_ref: ${{ github.base_ref }}" main
#          echo "github.head_ref: ${{ github.head_ref }}" parking/feature/TEST
#          echo "github.ref: ${{ github.ref }}" ref/heads/main
