name: Build Actions

on: [pull_request_target]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
# plan1. [을] 찾아서 label에 넣는다.
# plan2. PR 템플릿을 만들어서 선택한 것을 가져온다.    
      - name : Print Title of PR
        run: echo The Title of your PR is ${{ github.event.pull_request.title }}, {{ ./Todo/Info.plist }}
    
      - uses: actions/checkout@v2
      - uses: christianvuerings/add-labels@v1
        with:
          labels: |
            ${{ github.event.pull_request.title }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Lint code using SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
                  
      - name: Label from Info.plist
        uses: classpass/label-ios-version-info-plist-action@v1.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          info-plist-path: './Todo/Info.plist'
          label-format: 'iOS {version}' # optional
        
      - name: Prints the current branch name
        run: echo "${GITHUB_BRANCH##*/}"
        env:
          GITHUB_BRANCH: ${{ github.ref }}

      - name: Prints the current branch name
        run: echo "${GITHUB_REF#refs/heads/}"
        
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@master
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-west-2
          image: eng:${{ steps.extract_branch.outputs.branch }}
