name: check licenses

on: [ pull_request_target ]

jobs:
  build:
    runs-on: ubuntu-latest

jobs:
  license_check:
    runs-on: ubuntu-latest
    name: Check for unapproved licenses
    steps:
    - name: Checkout the code
      uses: actions/checkout@master
    - name: Perform checks
      id: license-check
      uses: ralexander-phi/license_approval@master
      with:
        package_manager: 'bundler'
