name: Create release

on:
  pull_request:
    branches:
      - dev
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.head.ref, 'release')

    steps:
      - uses: actions/checkout@v2

      - name: get App-version
        run: |
          TUIST_PATH="./Tuist/ProjectDescriptionHelpers/MainSetting.swift"
          step1=`sed -n '/let APP_VERSION/p' ${TUIST_PATH}`
          step2=`echo ${step1} | sed 's/let APP_VERSION = //g'`
          step3=`echo ${step2} | sed 's/"//g'`
          echo "APP_VERSION=${step3}" >> $GITHUB_ENV
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: version-${{ env.APP_VERSION }}
          release_name: version-${{ env.APP_VERSION }}
          body: version-${{ env.APP_VERSION }}
          draft: false
          prerelease: false

# TODO: APP_VERSION + 1 한 후에 dev에 commit + push 코드 필요
