name: Create release

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: get App-version
        run: |
          TUIST_PATH="./Tuist/ProjectDescriptionHelpers/MainSetting.swift"
          step1=`sed -n '/let APP_VERSION/p' ${TUIST_PATH}`
          step2=`echo ${step1} | sed 's/let APP_VERSION = //g'`
          step3=`echo ${step2} | sed 's/"//g'`
          echo "APP_VERSION=${step3}" >> $GITHUB_ENV
          BRANCH_TREE=${{ GITHUB_REF#refs/heads/ }}
          echo ${BRANCH_TREE}
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: version-${{ env.APP_VERSION }}
          release_name: version-${{ env.APP_VERSION }}
          body: version-${{ env.APP_VERSION }}
          draft: false
          prerelease: false
