name: Run TestCode

on: 
  pull_request:
    branches:    
      - '!release/**'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: "Run TestCode"
      run: |
        PRJOECT_NAME="Todo"
        PROJECT_SCHEME="Todo"
        xcodebuild clean test -project ${PRJOECT_NAME}.xcodeproj -scheme ${PROJECT_SCHEME} -destination "platform=iOS Simulator,name=iPhone 8" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
