name: SwiftLint

on:
  pull_request_target:
    paths:
      - '.github/workflows/codelint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
      
jobs:
  SwiftLint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run Swiftlint
        run: swiftlint --config .swiftlint.yml
