name: Lint code

on:
  pull_request_target:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run Swiftlint
        run: swiftlint --config .swiftlint.yml
